### ISSUE TITLE
Consider using LALRPOP

### ISSUE THREAD

**Issue by KiChjang** [salmans/rusty-razor#40]
I've been recently contributing to [chalk, the traits solver for rustc](https://github.com/rust-lang/chalk/) and they're currently using [LALRPOP](https://github.com/lalrpop/lalrpop) for their parsing needs. It has a separate file in which you define your grammar, which has a Rust-like syntax and looks almost like an ABNF form for your language. Maybe we can look into it so that you can easily add more tokens and production rules for razor in the future?

**Comment by KiChjang** [comment]
[This is how the grammar file looks like](https://github.com/rust-lang/chalk/blob/master/chalk-parse/src/parser.lalrpop).

**Comment by salmans** [comment]
This looks great! I definitely want to to give it a try.  The current parser in nom can be improved: I just worked on this PR: https://github.com/salmans/rusty-razor/pull/41/ for example but error handling is not good at all. So why not trying LALRPOP.
Alternatively, we can implement a TPTP in Rust and use it in Razor: http://www.tptp.org
